# Generated by Django 4.2 on 2024-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='num',
            field=models.BigIntegerField(default=1),
        ),
    ]
