# Generated by Django 4.2 on 2024-05-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashgen', '0003_delete_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=13)),
            ],
        ),
    ]
